### ISSUE TITLE
tt_print_form_schet depends on portal_sale 

### ISSUE THREAD

**Issue by yelizariev** [odoo-russia/odoo-russia#31]
Нужно добавить в зависимости

**Comment by dskarataev** [comment]
а что там такое в portal_sale, от чего зависит печатная форма? мы вообще портал не используем

**Comment by yelizariev** [comment]
В файле modules/tt_print_form_schet/sale_order_data.xml есть указание на portal_sale

record id="portal_sale.email_template_edi_sale" model="email.template"

**Comment by dskarataev** [comment]
исправил
