### ISSUE TITLE
В печатных формах ТОРГ-12 и Счет-фактура выводить цену товара без НДС

### ISSUE THREAD

**Issue by dskarataev** [odoo-russia/odoo-russia#7]
В ТОРГ-12 это колонка 11, в Счет-фактуре колонка 4. Выводить туда цену, поделенную на (1 + % налога, хранящийся в базе), тем самым получится цена без НДС.

**Comment by ivkond** [comment]
Исправлено в dd78857aa041162ae1091ddaf8e41ece445dc81c

**Comment by dskarataev** [comment]
требует доработки. пока оставляем висеть как есть. Дело в том, что при округлении цены получается такая штука, что цена без ндс не совпадает с суммой без ндс, и при изменении даже одной копейки в цене, могут быть сильные расхождения.

**Comment by dskarataev** [comment]
все хорошо, закрываю.
